[default]

machines = [
    "abc1234"
]

[default.db]
endpoints = [ "https://localhost:5432" ]
user = "vicky"
database = "vicky"
password = "vicky"


[default.s3_config]
endpoint = "http://localhost:9000"
access_key_id = "minio"
secret_access_key = "aichudiKohr6aithi4ahh3aeng2eL7xo"
region = "us-east-1"
log_bucket = "vicky-logs"

[default.oidc_config]
jwks_url = ""

