ALTER TABLE tasks ALTER COLUMN "created_at" TYPE TIMESTAMP USING "created_at" AT TIME ZONE 'UTC';
ALTER TABLE tasks ALTER COLUMN "finished_at" TYPE TIMESTAMP USING "finished_at" AT TIME ZONE 'UTC';
ALTER TABLE tasks ALTER COLUMN "claimed_at" TYPE TIMESTAMP USING "claimed_at" AT TIME ZONE 'UTC';
ALTER TABLE tasks ALTER COLUMN "last_heartbeat" TYPE TIMESTAMP USING last_heartbeat AT TIME ZONE 'UTC';
