ALTER TABLE tasks ALTER COLUMN "created_at" TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE tasks ALTER COLUMN "finished_at" TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE tasks ALTER COLUMN "claimed_at" TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE tasks ALTER COLUMN "last_heartbeat" TYPE TIMESTAMP WITH TIME ZONE;
